### PR TITLE
Add support for Laravel Telescope

### PR DESCRIPTION
**Pull request by stelgenhof**
This PR adds support for Laravel's Telescope commands `telescope:prune` and `telescope:clear`. 
I've added an 'how-to' in the documentations section how it can be used.

Cheers! Sacha

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi Sacha 👋 

Thanks for your contribution. That's a very impressive PR, you didn't miss one spot haha.

Just before I merge, I'm not sure about adding another question in the `deploy:init` command for cleaning telescope entries. It's definitely a good addition but not something people are going to want often enough to provide a shortcut for them.

You've even written a very nice "How to" section so they won't be lost if they need to add it to their config file. What do you think?

Thanks again for your amazing work. 💯

**Comment by stelgenhof** [comment]
Thanks @lorisleiva!

As for the `deploy:init` for me either way is good. I just followed the implementation for `artisan:horizon:terminate` :) I can remove it if you prefer it that way.

Thanks! Sacha

**Comment by lorisleiva** [comment]
If you don't mind that'd be great otherwise I can always rectify after merging.

I'm just trying to account for the 20% of settings that works for 80% of users and (at the moment) I'm not sure that telescope pruning is part of that. Thanks again! 🙂

**Comment by stelgenhof** [comment]
Sure, I will do that. I agree that maybe Telescope pruning isn't something users will need that often in a deployment situation. I just happened to have a need for it; that's why this PR ;)

**Comment by stelgenhof** [comment]
@lorisleiva Updated the PR.

**Pull request merged**
