### PR TITLE
Fix for issue #179

### PR DESCRIPTION
**Pull request by ChafikHadjAbdouRazack**

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi! Thanks for that! This look good to me but I can't merge it due to conflicting files. Not sure why though since I haven't pushed anything to master today. Could you please resolve the conflict so I can merge this? 🙂

**Comment by ChafikHadjAbdouRazack** [comment]
It's OK now you can merge it @lorisleiva .

**Comment by lorisleiva** [comment]
Thank you 🍺

**Comment by ChafikHadjAbdouRazack** [comment]
C'était un plaisir pour moi. J'utilise le package au quotidien pour le déploiement de projet Laravel.

**Pull request merged**
