### PR TITLE
Added use of the yarn package manager

### PR DESCRIPTION
**Pull request by andrey-helldar**
See https://deployer.org/recipes/yarn

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for this awesome contribution!

I will merge this ASAP and adjust the `deploy:init` command so that it doesn't ask twice about npm or yarn but rather increase the options available.

**Comment by andrey-helldar** [comment]
Hi!
What to make priority - npm or yarn?

**Comment by lorisleiva** [comment]
I was more thinking something like:

```php
$this->choice(
    'Do you want to compile your asset during deployment ?',
    [
        'No',
        'Yes using `npm run production`',
        'Yes using `yarn production`'
    ],
    1
);
```

I don't think that many people will want to use the `development` script for their production servers so I think it's okay to just leave it out and make the initialization simpler and more realistic.

What do you think?

**Comment by andrey-helldar** [comment]
I think you are right. Now I will add the commit correcting it.

**Comment by andrey-helldar** [comment]
Clear code is:
```php
public function defineAdditionalHooks()
{
    $npm = $this->choice(
        'Do you want to compile your asset during deployment with npm/yarn?',
        [
            'No',
            'Yes using `npm run production`',
            'Yes using `npm run development`',
            'Yes using `yarn production`',
            'Yes using `yarn development`',
        ], 1
    );

    if ($npm === 'Yes using `npm run production`') {
        $this->addHooksCompileAssets('npm', 'production');
    }

    if ($npm === 'Yes using `npm run development`') {
        $this->addHooksCompileAssets('npm', 'development');
    }

    if ($npm === 'Yes using `yarn production`') {
        $this->addHooksCompileAssets('yarn', 'production');
    }

    if ($npm === 'Yes using `yarn development`') {
        $this->addHooksCompileAssets('yarn', 'development');
    }

    // other methods
}

private function addHooksCompileAssets($manager, $environment)
{
    $this->builder->add('hooks.build', "$manager:install");
    $this->builder->add('hooks.build', "$manager:$environment");
}
```

**Comment by andrey-helldar** [comment]
My commit has been [pulled](https://github.com/lorisleiva/laravel-deployer/pull/52/commits/06823d598f90326aa4e57327aeba0e4b163526e8).

**Comment by lorisleiva** [comment]
Okay thanks, so you think we should keep the options `npm run development` and `yarn development`?

**Comment by andrey-helldar** [comment]
yarn works better with multi-thread dependency installation, and also has improved cache performance.

**Comment by lorisleiva** [comment]
No I'm not talking about this. I'm obviously glad to add `yarn` to Laravel Deployer.

I just think that the options using the `development` environment are not very necessary when deploying.

```php
[
    'No',
    'Yes using `npm run production`',
    'Yes using `npm run development`', // Remove
    'Yes using `yarn production`',
    'Yes using `yarn development`', // Remove
]
```

What do you think?

**Comment by andrey-helldar** [comment]
Sorry. Translation difficulties.Indeed, I think that the production server does not need to compile the dev version of resoirces. And in those rare cases when someone needs this approach, they will be able to compile resources on their computer.

**Comment by andrey-helldar** [comment]
I corrected the code

**Comment by lorisleiva** [comment]
@jlsjonas Definitely agree with that. I've also gone back to npm but, the fact is, a lot of people have switched to yarn. I think it would be a good idea to make it easier for them to use Laravel Deployer. Do you not agree?

**Comment by fgilio** [comment]
Hi guys! My 2 cents here: We use `yarn` and had to use a custom task. So, this would be a nice addition imo, and I guess it does not add that much complexity.

https://iamturns.com/yarn-vs-npm-2018/ Nice post btw.

**Comment by lorisleiva** [comment]
Alright let's do this! Thanks again for this PR @andrey-helldar 🙏 

If anyone could double check this PR by using the new `yarn` tasks I will tag a release right after that.

**Comment by fgilio** [comment]
Hmm just tried to test this locally but I it seems I have something misconfigured with the SSH connection to the server, will try again later.

**Comment by jlsjonas** [comment]
@lorisleiva I know a lot have switched to yarn when it was the better option (I used it too at some point), but this is likely to create confusion for those who haven't used the node a lot.
Maybe (not that I want to introduce bias...) add a `(recommended)` next to npm? in the docs maybe?

**Comment by andrey-helldar** [comment]
@lorisleiva , I can check on the weekend.

**Comment by andrey-helldar** [comment]
@jlsjonas, My PR affects [documentation](https://github.com/lorisleiva/laravel-deployer/pull/52/commits/aaca87af408f1d2a74cbc6f916827717f6c392c2#diff-e70100059cc3a7376740bbe9751a082e)

**Comment by andrey-helldar** [comment]
PR for fix #52 `Task yarn:install not found`

**Comment by jlsjonas** [comment]
@andrey-helldar I see that :) but doesn't include anything related to my comment :)

**Comment by lorisleiva** [comment]
@jlsjonas In my [latest commit](https://github.com/lorisleiva/laravel-deployer/commit/548cf82f3fc63ff167e3e29f73ac6976bf4da6ea), I've merge the docs for npm and yarn with an emphasis on npm (yarn shown as an alternative). I wasn't a big fan of having to duplicate the documentation for essentially the same feature.

**Pull request merged**
